[package]
name = "template"
version = "0.1.0"
edition = "2021"
authors = ["waver <arkvaer@gmail.com>"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

